version: '2'

services:
  api:
    volumes:
      - ./services/api/src:/var/lib/app
      - ./services/api/scripts:/home/docker
      - ./services/core:/var/lib/core
      # prevent mounting node_modules to avoid cross-platform incompatibilities
      - /var/lib/app/node_modules
    entrypoint: /home/docker/startup.integration.sh
