version: '2'

services:
  db:
    image: postgres:9
    ports:
      - "5430:5432" # in order to avoid conflicts with running instances of pg
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    labels:
      container_group: service
    expose:
      - "5430"
  api:
    build:
      context: ./services
      dockerfile: ./api/Dockerfile
    image: agavelab/backendbase-api
    links:
      - db
    environment:
      AWS_SM_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_NAME: user
      DB_HOST: db
    ports:
      - "3000:3000"
    labels:
      container_group: service
